# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-29 14:12
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(blank=True, max_length=200, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('service_image', models.ImageField(blank=True, upload_to='image/', verbose_name='\u0417\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u043d\u044f')),
                ('service_text', ckeditor.fields.RichTextField(blank=True, verbose_name='\u041e\u0441\u043d\u043e\u0432\u043d\u0430 \u0447\u0430\u0441\u0442\u0438\u043d\u0430')),
                ('service_date', models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0456\u043a\u0430\u0446\u0456\u0457')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='\u0412\u0456\u0434\u0435\u043e')),
            ],
            options={
                'db_table': 'Service',
                'verbose_name': '\u0421\u0435\u0440\u0432\u0456\u0441',
                'verbose_name_plural': '\u0421\u0435\u0440\u0432\u0456\u0441\u0438',
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-news_date'], 'verbose_name': '\u041d\u043e\u0432\u0438\u043d\u0438 \u0444\u0456\u0440\u043c\u0438', 'verbose_name_plural': '\u041d\u043e\u0432\u0438\u043d\u0438 \u0444\u0456\u0440\u043c\u0438'},
        ),
        migrations.AlterField(
            model_name='news',
            name='news_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 5, 29, 14, 11, 38, 5661, tzinfo=utc), verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0456\u043a\u0430\u0446\u0456\u0457'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='news_text',
            field=ckeditor.fields.RichTextField(blank=True, default=datetime.datetime(2017, 5, 29, 14, 11, 55, 790193, tzinfo=utc), verbose_name='\u041e\u0441\u043d\u043e\u0432\u043d\u0430 \u0447\u0430\u0441\u0442\u0438\u043d\u0430'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='news_title',
            field=models.CharField(blank=True, default=datetime.datetime(2017, 5, 29, 14, 12, 4, 246773, tzinfo=utc), max_length=200, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043d\u043e\u0432\u0438\u043d\u0438'),
            preserve_default=False,
        ),
    ]
