# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-31 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_auto_20170529_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_speed', models.CharField(blank=True, max_length=100, verbose_name='\u0412\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u0430 \u0448\u0432\u0438\u0434\u043a\u0456\u0441\u0442\u044c')),
                ('tariff_lviv', models.CharField(blank=True, max_length=100, verbose_name='\u043c. \u041b\u044c\u0432\u0456\u0432 + 30\u043a\u043c')),
                ('tariff_oblast', models.CharField(blank=True, max_length=100, verbose_name='\u041e\u0431\u043b\u0430\u0441\u0442\u044c (\u0411\u0440\u043e\u0434\u0456\u0432\u0441\u044c\u043a\u0438\u0439 \u0440-\u043d., \u0421\u043a\u043e\u043b\u0456\u0432\u0441\u044c\u043a\u0438\u0439 \u0440-\u043d \u0441\u043c\u0442. \u0421\u043b\u0430\u0432\u0441\u044c\u043a\u0435 \u0442\u0430 \u0434\u043e\u0432\u043a\u043e\u043b\u0430')),
                ('tariff_district', models.CharField(blank=True, max_length=100, verbose_name='\u0406\u043d\u0448\u0456 \u0440\u0430\u0439\u043e\u043d\u0438')),
                ('tariff_date', models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0456\u043a\u0430\u0446\u0456\u0457')),
            ],
            options={
                'db_table': 'Tariff',
                'verbose_name': '\u0422\u0430\u0440\u0438\u0444\u0438 \u0434\u043b\u044f \u0444\u0456\u0437\u0438\u0447\u043d\u0438\u0445 \u043e\u0441\u0456\u0431',
                'verbose_name_plural': '\u0422\u0430\u0440\u0438\u0444\u0438 \u0434\u043b\u044f \u0444\u0456\u0437\u0438\u0447\u043d\u0438\u0445 \u043e\u0441\u0456\u0431',
            },
        ),
    ]
