# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-31 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0003_tariff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_speed', models.CharField(blank=True, max_length=100, verbose_name='\u0412\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u0430 \u0448\u0432\u0438\u0434\u043a\u0456\u0441\u0442\u044c')),
                ('tariff_lviv', models.CharField(blank=True, max_length=100, verbose_name='\u043c. \u041b\u044c\u0432\u0456\u0432 + 30\u043a\u043c')),
                ('tariff_oblast', models.CharField(blank=True, max_length=100, verbose_name='\u041e\u0431\u043b\u0430\u0441\u0442\u044c')),
                ('tariff_dinip', models.CharField(blank=True, max_length=100, verbose_name='\u0414\u0438\u043d\u0430\u043c\u0456\u0447\u043d\u0430 \u0406\u0420-\u0430\u0434\u0440\u0435\u0441\u0430')),
                ('tariff_statip', models.CharField(blank=True, max_length=100, verbose_name='\u0421\u0442\u0430\u0442\u0438\u0447\u043d\u0430 \u0406\u0420-\u0430\u0434\u0440\u0435\u0441\u0430')),
                ('tariff_date', models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0456\u043a\u0430\u0446\u0456\u0457')),
            ],
            options={
                'db_table': 'Tarifu',
                'verbose_name': '\u0422\u0430\u0440\u0438\u0444\u0438 \u0434\u043b\u044f \u044e\u0440\u0438\u0434\u0438\u0447\u043d\u0438\u0445 \u043e\u0441\u0456\u0431',
                'verbose_name_plural': '\u0422\u0430\u0440\u0438\u0444\u0438 \u0434\u043b\u044f \u044e\u0440\u0438\u0434\u0438\u0447\u043d\u0438\u0445 \u043e\u0441\u0456\u0431',
            },
        ),
    ]
