# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-31 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0004_tarifu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarifu',
            old_name='tariff_date',
            new_name='tarifu_date',
        ),
        migrations.RenameField(
            model_name='tarifu',
            old_name='tariff_dinip',
            new_name='tarifu_dinip',
        ),
        migrations.RenameField(
            model_name='tarifu',
            old_name='tariff_lviv',
            new_name='tarifu_lviv',
        ),
        migrations.RenameField(
            model_name='tarifu',
            old_name='tariff_oblast',
            new_name='tarifu_oblast',
        ),
        migrations.RenameField(
            model_name='tarifu',
            old_name='tariff_speed',
            new_name='tarifu_speed',
        ),
        migrations.RenameField(
            model_name='tarifu',
            old_name='tariff_statip',
            new_name='tarifu_statip',
        ),
    ]
