# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-31 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0005_auto_20170531_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifdd_title', models.CharField(blank=True, max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430 \u043e\u043f\u043b\u0430\u0442\u0438')),
                ('tarifdd_pay', models.CharField(blank=True, max_length=100, verbose_name='\u0446\u0456\u043d\u0430')),
                ('tarifdd_date', models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0456\u043a\u0430\u0446\u0456\u0457')),
            ],
            options={
                'db_table': 'Taridd',
                'verbose_name': '\u0414\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u0456 \u043e\u043f\u043b\u0430\u0442\u0438',
                'verbose_name_plural': '\u0414\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u0456 \u043e\u043f\u043b\u0430\u0442\u0438',
            },
        ),
    ]
