# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-31 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0006_tarifdd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adressa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adressa_adressa', models.CharField(blank=True, max_length=200, verbose_name='\u0410\u0434\u0440\u0435\u0441\u0441\u0430 \u0444\u0456\u0440\u043c\u0438')),
            ],
            options={
                'db_table': 'Adressa',
                'verbose_name': '\u0410\u0434\u0440\u0435\u0441\u0441\u0430 \u0444\u0456\u0440\u043c\u0438',
                'verbose_name_plural': '\u0410\u0434\u0440\u0435\u0441\u0441\u0430 \u0444\u0456\u0440\u043c\u0438',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_nn', models.CharField(blank=True, max_length=100, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u043f\u043e \u043f\u043e\u0440\u044f\u0434\u043a\u0443')),
                ('email_viddil', models.CharField(blank=True, max_length=100, verbose_name='\u0412\u0456\u0434\u0434\u0456\u043b')),
                ('email_email', models.CharField(blank=True, max_length=100, verbose_name='\u0415\u043b\u0435\u043a\u0442\u0440\u043e\u043d\u043d\u0430 \u0430\u0434\u0440\u0435\u0441\u0430')),
                ('email_date', models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0456\u043a\u0430\u0446\u0456\u0457')),
            ],
            options={
                'db_table': 'Email',
                'verbose_name': '\u0415\u043b\u0435\u043a\u0442\u0440\u043e\u043d\u043d\u0430 \u043f\u043e\u0448\u0442\u0430',
                'verbose_name_plural': '\u0415\u043b\u0435\u043a\u0442\u0440\u043e\u043d\u043d\u0430 \u043f\u043e\u0448\u0442\u0430',
            },
        ),
        migrations.CreateModel(
            name='Telefon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon_nn', models.CharField(blank=True, max_length=100, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u043f\u043e \u043f\u043e\u0440\u044f\u0434\u043a\u0443')),
                ('telefon_telefon', models.CharField(blank=True, max_length=100, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('telefon_viddil', models.CharField(blank=True, max_length=100, verbose_name='\u0412\u0456\u0434\u0434\u0456\u043b')),
                ('telefon_date', models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0456\u043a\u0430\u0446\u0456\u0457')),
            ],
            options={
                'db_table': 'Telefon',
                'verbose_name': '\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u043d\u0456 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0438',
                'verbose_name_plural': '\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u043d\u0456 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0438',
            },
        ),
    ]
