# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-02 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0007_adressa_email_telefon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='\u041d\u0430\u0437\u0432\u0430')),
                ('description', models.ImageField(upload_to=b'', verbose_name='\u041e\u043f\u0438\u0441')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u041a\u043e\u043d\u0442\u0435\u0439\u043d\u0435\u0440 \u0444\u043e\u0442\u043e\u0433\u0430\u043b\u0435\u0440\u0435\u0457',
                'verbose_name_plural': '\u041a\u043e\u043d\u0442\u0435\u0439\u043d\u0435\u0440 \u0444\u043e\u0442\u043e\u0433\u0430\u043b\u0435\u0440\u0435\u0457',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430')),
                ('image', models.ImageField(blank=True, upload_to='image/fotogalery/', verbose_name='\u0417\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u043d\u044f')),
                ('caption', models.CharField(blank=True, max_length=250, verbose_name='\u041f\u0456\u0434\u043f\u0438\u0441')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.Item')),
            ],
            options={
                'ordering': ['title'],
                'verbose_name': '\u0424\u043e\u0442\u043e\u0433\u0430\u043b\u0435\u0440\u0435\u044f',
                'verbose_name_plural': '\u0424\u043e\u0442\u043e\u0433\u0430\u043b\u0435\u0440\u0435\u044f',
            },
        ),
    ]
