# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-02 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0008_item_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name'], 'verbose_name': '\u0424\u043e\u0442\u043e\u0433\u0430\u043b\u0435\u0440\u0435\u044f', 'verbose_name_plural': '\u0424\u043e\u0442\u043e\u0433\u0430\u043b\u0435\u0440\u0435\u044f'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['title'], 'verbose_name': '\u0444\u043e\u0442\u043e', 'verbose_name_plural': '\u0444\u043e\u0442\u043e'},
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(verbose_name='\u041e\u043f\u0438\u0441 \u0444\u043e\u0442\u043e\u0433\u0430\u043b\u0435\u0440\u0435\u0457'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=250, verbose_name='\u041d\u0430\u0437\u0432\u0430 \u0444\u043e\u0442\u043e\u0433\u0430\u043b\u0435\u0440\u0435\u0457'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430 \u0444\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0456\u0457'),
        ),
    ]
