# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-05 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0017_auto_20170603_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_title', models.CharField(blank=True, max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430 \u0444\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0456\u0457')),
                ('photo_image', models.ImageField(blank=True, upload_to='image/fotogalery/', verbose_name='\u0417\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u043d\u044f')),
                ('photo_caption', models.CharField(blank=True, max_length=250, verbose_name='\u041f\u0456\u0434\u043f\u0438\u0441')),
                ('photo_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.Item')),
            ],
            options={
                'ordering': ['photo_title'],
                'verbose_name': '\u0444\u043e\u0442\u043e',
                'verbose_name_plural': '\u0444\u043e\u0442\u043e',
            },
        ),
        migrations.RemoveField(
            model_name='photo',
            name='item',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
