# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-13 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0021_auto_20170613_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_image',
            field=models.ImageField(blank=True, upload_to='service/', verbose_name='\u0417\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u043d\u044f'),
        ),
    ]
